In [12]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load the dataset

In [13]:

# Load dataset
df = pd.read_csv("cardio.csv")

print("Original Data:\n", df.head())

Original Data:
    id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0   0  18393       2     168    62.0    110     80            1     1      0
1   1  20228       1     156    85.0    140     90            3     1      0
2   2  18857       1     165    64.0    130     70            3     1      0
3   3  17623       2     169    82.0    150    100            1     1      0
4   4  17474       1     156    56.0    100     60            1     1      0

   alco  active  cardio
0     0       1       0
1     0       1       1
2     0       0       1
3     0       1       1
4     0       0       0

In [14]:

df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

# Data Cleaning

In [15]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Drop 'id' column (not useful for prediction)
df.drop('id', axis=1, inplace=True)

df['age'] = df['age'] / 365
df.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,50.391781,2,168,62.0,110,80,1,1,0,0,1,0
1,55.419178,1,156,85.0,140,90,3,1,0,0,1,1
2,51.663014,1,165,64.0,130,70,3,1,0,0,0,1
3,48.282192,2,169,82.0,150,100,1,1,0,0,1,1
4,47.873973,1,156,56.0,100,60,1,1,0,0,0,0

# Handling Missing Values

In [16]:
df.isnull().sum()

df = df.fillna(df.mean(numeric_only=True))

# Encoding categorical data

In [17]:
le = LabelEncoder()

for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])

# FEATURE SELECTION

In [18]:
# Correlation with target
correlation = df.corr()
target_corr = correlation['cardio'].abs()

# Select important features
selected_features = target_corr[target_corr > 0.1].index

df = df[selected_features]

print("\nSelected Features:\n", selected_features)

Selected Features:
 Index(['age', 'weight', 'cholesterol', 'cardio'], dtype='object')

#  TRAIN-TEST SPLIT

In [19]:
X = df.drop('cardio', axis=1)
y = df['cardio']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("\nTrain Shape:", X_train.shape)
print("Test Shape:", X_test.shape)

Train Shape: (56000, 3)
Test Shape: (14000, 3)

In [20]:
df.head()

         age  weight  cholesterol  cardio
0  50.391781    62.0            1       0
1  55.419178    85.0            3       1
2  51.663014    64.0            3       1
3  48.282192    82.0            1       1
4  47.873973    56.0            1       0